/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;



/**
 *
 * @author adolf
 */
public class Ventana_principal_invetario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_principal_invetario.class.getName());

    /**
     * Creates new form Ventana_arbol
     */
    
    
    
    private DefaultTreeModel modelo;
    private DefaultMutableTreeNode nodoSeleccionado;
    private DefaultTableModel modeloTabla;
    private DefaultTableModel modeloTabla2;
    /* metodo imagenes*/
    
    private void mostrarContenido(String nombreNodo) {
    // Reinicia todo
    panelColor.setBackground(null);
    lblImagen.setIcon(null);
    lblImagen.setText("");

    switch (nombreNodo.toLowerCase()) {
        // Colores → se pintan en el panel
        case "rojo":
            panelColor.setBackground(Color.RED);
            break;
        case "verde":
            panelColor.setBackground(Color.GREEN);
            break;
        case "azul":
            panelColor.setBackground(Color.BLUE);
            break;

        //  Autos → se muestran en el label
        case "skin":
            mostrarImagen("/img/skin.png");
            break;
        case "nails":
            mostrarImagen("/img/nails.png");
            break;
        case "avion":
            mostrarImagen("/img/avion.png");
            break;

        //  Animales
        case "perro":
            mostrarImagen("/img/perro.png");
            break;
        case "gato":
            mostrarImagen("/img/gato.png");
            break;
        case "raton":
            mostrarImagen("/img/raton.png");
            break;

        default:
            // Si el nodo no tiene color ni imagen
            lblImagen.setText("Sin contenido visual");
    }
}

    private void mostrarImagen(String ruta) {
    java.net.URL url = getClass().getResource(ruta);
    if (url != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);
        lblImagen.setIcon(icon);
    } else {
        lblImagen.setText("Imagen no encontrada");
    }
    }
    
    
    
    public Ventana_principal_invetario() {
        initComponents();
        
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        tablaarticulo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaarticulo2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaarticulo.setFillsViewportHeight(true);
        tablaarticulo2.setFillsViewportHeight(true);
        
    addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            int ancho = getWidth();
            int alto = getHeight();

            int margenIzq = 560; // distancia desde el borde izquierdo
            int margenSup = 20;  // espacio superior
            int espacioEntre = 30; // separación entre tablas

            int anchoTablas = ancho - margenIzq - 40;
            int altoMitad = (alto - 2 * margenSup - espacioEntre) / 2;

            // --- primera tabla arriba ---
            jScrollPane2.setBounds(margenIzq, margenSup, anchoTablas, altoMitad);

            // --- segunda tabla abajo ---
            jScrollPane3.setBounds(margenIzq, margenSup + altoMitad + espacioEntre, anchoTablas, altoMitad);
        }
    });


        



        
        modeloTabla = new DefaultTableModel(
        new Object[]{"articulo", "tipo de art.", "entrada", "salida", "stock"}, 0
    );
    tablaarticulo.setModel(modeloTabla);

    
     modeloTabla2 = new DefaultTableModel(
    new Object[]{"articulo", "tipo de art.", "entrada", "salida", "stock"}, 0
     );
     tablaarticulo2.setModel(modeloTabla2);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        btn_modelo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        panelColor = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaarticulo = new javax.swing.JTable();
        btn_c_salida = new javax.swing.JButton();
        btn_articulo = new javax.swing.JButton();
        btn_c_entrada = new javax.swing.JButton();
        txtarticulo = new javax.swing.JTextField();
        txtsalida = new javax.swing.JTextField();
        txtentrada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txttipo = new javax.swing.JTextField();
        btn_entrada = new javax.swing.JButton();
        btn_salida = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaarticulo2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 6, 180, 440));

        btn_modelo.setText("cargar modelo");
        btn_modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modeloMouseClicked(evt);
            }
        });
        btn_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modeloActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btn_guardar.setText("Guradar");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 110, -1));

        btn_modificar.setText("Modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 110, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 200, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 200, 30));

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 140, 110));

        lblImagen.setText("jLabel1");
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 120, 30));

        tablaarticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Articulo", "Tipo de Art.", "Entradas", "Salidas", "Stock"
            }
        ));
        jScrollPane2.setViewportView(tablaarticulo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 390, 250));

        btn_c_salida.setText("Cantidad Salida");
        btn_c_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c_salidaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 130, -1));

        btn_articulo.setText("Articulo");
        getContentPane().add(btn_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 130, -1));

        btn_c_entrada.setText("Cantidad Entrada");
        getContentPane().add(btn_c_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        txtarticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtarticuloActionPerformed(evt);
            }
        });
        getContentPane().add(txtarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 150, -1));
        getContentPane().add(txtsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 150, -1));
        getContentPane().add(txtentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 150, -1));

        jButton1.setText("Tipo de Articulo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, -1));

        txttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoActionPerformed(evt);
            }
        });
        getContentPane().add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 150, -1));

        btn_entrada.setText("Entrada");
        btn_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entradaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        btn_salida.setText("Salida");
        btn_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salidaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, -1, -1));

        tablaarticulo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Articulo", "Tipo de Art.", "Entrada", "Salida", "Stock"
            }
        ));
        jScrollPane3.setViewportView(tablaarticulo2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 380, 240));

        jLabel1.setText("Historial Stock");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        jLabel2.setText("Ultimo movimiento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modeloActionPerformed
        
    }//GEN-LAST:event_btn_modeloActionPerformed

    private void btn_modeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modeloMouseClicked
       modelo = new DefaultTreeModel(new DefaultMutableTreeNode("Productos"));
       jTree1.setModel(modelo);
    }//GEN-LAST:event_btn_modeloMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        String texto = this.jTextField1.getText();
        DefaultMutableTreeNode n = new DefaultMutableTreeNode(texto);
        if(nodoSeleccionado != null){
            modelo.insertNodeInto(n, nodoSeleccionado,nodoSeleccionado.getChildCount());
        }
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
       nodoSeleccionado = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
    if (nodoSeleccionado != null) {
        String nombreNodo = nodoSeleccionado.getUserObject().toString();
        this.jTextField2.setText(nombreNodo);
        mostrarContenido(nombreNodo);}
    
    }//GEN-LAST:event_jTree1ValueChanged

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        if(nodoSeleccionado!= null){
        modelo.removeNodeFromParent(nodoSeleccionado);
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        if(nodoSeleccionado !=null){
        nodoSeleccionado.setUserObject(this.jTextField2.getText());
        modelo.nodeChanged(nodoSeleccionado);
        }
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_c_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c_salidaActionPerformed

    private void txtarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtarticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtarticuloActionPerformed

    private void txttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entradaActionPerformed
        // TODO add your handling code here:
       String articulo = txtarticulo.getText().trim();
    String tipo = txttipo.getText().trim();
    String entradaTexto = txtentrada.getText().trim();

    if (articulo.isEmpty() || tipo.isEmpty() || entradaTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa todos los campos antes de registrar la entrada.");
        return;
    }

    int entrada;
    try {
        entrada = Integer.parseInt(entradaTexto);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La entrada debe ser un número.");
        return;
    }

    boolean existe = false;

    // Buscar si el artículo ya existe en la tabla principal
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        if (modeloTabla.getValueAt(i, 0).toString().equalsIgnoreCase(articulo)) {
            int stockactual = Integer.parseInt(modeloTabla.getValueAt(i, 4).toString());
            int nuevostock = stockactual + entrada;
            modeloTabla.setValueAt(entrada, i, 2);   // entrada
            modeloTabla.setValueAt("", i, 3);        // limpiar salida
            modeloTabla.setValueAt(nuevostock, i, 4);
            existe = true;
            break;
        }
    }

    // Si no existe, lo agregamos como nuevo
    if (!existe) {
        modeloTabla.addRow(new Object[]{articulo, tipo, entrada, "", entrada});
    }

    // Agregar movimiento al historial (tablaarticulo2)
    modeloTabla2.addRow(new Object[]{articulo, tipo, entrada, "", getStockActual(articulo)});

    // Limpiar campos
    txtarticulo.setText("");
    txttipo.setText("");
    txtentrada.setText("");
    }//GEN-LAST:event_btn_entradaActionPerformed

    private void btn_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidaActionPerformed
        // TODO add your handling code here:
        String articulo = txtarticulo.getText().trim();
    String tipo = txttipo.getText().trim();
    String salidaTexto = txtsalida.getText().trim();

    if (articulo.isEmpty() || tipo.isEmpty() || salidaTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa todos los campos antes de registrar la salida.");
        return;
    }

    int salida;
    try {
        salida = Integer.parseInt(salidaTexto);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La salida debe ser un número.");
        return;
    }

    boolean encontrado = false;

   
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        if (modeloTabla.getValueAt(i, 0).toString().equalsIgnoreCase(articulo)) {
            int stockactual = Integer.parseInt(modeloTabla.getValueAt(i, 4).toString());
            int nuevostock = stockactual - salida;
            if (nuevostock < 0) nuevostock = 0;

            modeloTabla.setValueAt("", i, 2);     
            modeloTabla.setValueAt(salida, i, 3);  
            modeloTabla.setValueAt(nuevostock, i, 4);
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        javax.swing.JOptionPane.showMessageDialog(this, "El artículo no existe en la tabla principal.");
    } else {
        
        modeloTabla2.addRow(new Object[]{articulo, tipo, "", salida, getStockActual(articulo)});
    }
    txtarticulo.setText("");
    txttipo.setText("");
    txtsalida.setText("");
    }//GEN-LAST:event_btn_salidaActionPerformed
private int getStockActual(String articulo) {
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        if (modeloTabla.getValueAt(i, 0).toString().equalsIgnoreCase(articulo)) {
            return Integer.parseInt(modeloTabla.getValueAt(i, 4).toString());
        }
    }
    return 0;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana_principal_invetario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_articulo;
    private javax.swing.JButton btn_c_entrada;
    private javax.swing.JButton btn_c_salida;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_entrada;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modelo;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel panelColor;
    private javax.swing.JTable tablaarticulo;
    private javax.swing.JTable tablaarticulo2;
    private javax.swing.JTextField txtarticulo;
    private javax.swing.JTextField txtentrada;
    private javax.swing.JTextField txtsalida;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
